version: '3.8'
services:
  mongodb-game:
    image: mongo
    container_name: mongodb-game
    ports:
      - 27018:27017
    volumes:
      - data-game:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
  mongo-express-game:
    image: mongo-express
    container_name: mongo-express-game
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb-game
volumes:
  data-game: {}
networks:
  default:
    name: mongodb_network_game